//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryShop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaundryShop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We clean your carpets!.
        /// </summary>
        internal static string CarpetCleanDescription {
            get {
                return ResourceManager.GetString("CarpetCleanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What..
        /// </summary>
        internal static string Comforter {
            get {
                return ResourceManager.GetString("Comforter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindly check your order(s)..
        /// </summary>
        internal static string ConfirmHeaderText {
            get {
                return ResourceManager.GetString("ConfirmHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanna do things the old fashioned way? We can do that for you..
        /// </summary>
        internal static string HandWashDescription {
            get {
                return ResourceManager.GetString("HandWashDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you been here before?.
        /// </summary>
        internal static string LogInHeaderText {
            get {
                return ResourceManager.GetString("LogInHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! What can we do for you?.
        /// </summary>
        internal static string OrderHeaderText {
            get {
                return ResourceManager.GetString("OrderHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may not lift, but we press.Hard. Huzzah!.
        /// </summary>
        internal static string PressDescription {
            get {
                return ResourceManager.GetString("PressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We wash your clothes, then fold them. Ha!.
        /// </summary>
        internal static string WashFoldDescription {
            get {
                return ResourceManager.GetString("WashFoldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We wash your clothes, then press them. Beat that!.
        /// </summary>
        internal static string WashPressDescription {
            get {
                return ResourceManager.GetString("WashPressDescription", resourceCulture);
            }
        }
    }
}
